### PR TITLE
Update when its different version instead of lower

### PR DESCRIPTION
**Pull request by TheMulhima**
reasoning: https://github.com/hk-modding/modlinks/pull/763

### CODE REVIEW

**Comment by fifty-six** [comment]
I dislike this from a versioning point of view tbh. If someone releases something broken I'd prefer for them to fix it and bump the version or something honestly. I believe other things which handle packages/deps/etc. do this similarly? I could still be convinced otherwise though

**Comment by TheMulhima** [comment]
Well what happened in this case (linked above) was that the broken mod (failed to init for some reason) was added on 30 October, the author went offline and returned on 30th November to finally update it. In between that month they didn't push a new fixed release for whatever reason and we couldn't really do anything about it other than revert to old working version but that didn't fix anything for the people who already had the mod as scarab didn't prompt to update the mod.

**Comment by fifty-six** [comment]
I mean you can bump the version while providing the old mod if *really* needed, though I'd be interested in additional feedback if several other people also feel this is necessary.

**Comment by SFGrenade** [comment]
from a versioning point of view, yes, that would not be great, **but.**

for version control, one could also allow users to downdate their version, in case of actual package managers one has to specify the version and force the "up"date to a lower version.

so i could see it being allowed, but only after the user explicitly pressed a downgrade button or something

**Comment by fifty-six** [comment]
I'm closing this, at least for now. If we're gonna do this it'd be a downgrade button and all.

**Pull request closed without merging**
