### PR TITLE
Modded is no longer identified as Vanilla

### LINKED ISSUE #67: Handle case when the API is already installed
Scarab assumes the game is clean when opening it up for the first time, and it makes a backup of `Assembly-CSharp.dll` when installing the modding API. However, for those of us who were using the previous mod installer and already had that file patched, this backup is actually a modded backup. So when pressing "Disable API", the game is still modded.
That's quite confusing, maybe we could add a warning if the original file doesn't match the expected hash?

### PR DESCRIPTION
**Pull request by HKLab**
Fix #67

### CODE REVIEW

**Comment by fifty-six** [comment]
I don't want to load the assembly to check if it's vanilla, that was a fairly explicit choice in the design. Having Mono.Cecil as a dependency is about 6 layers of overkill and loading assemblies at all is something I've been very much avoiding.

**Comment by HKLab** [comment]
So how do you want to implement this feature?

**Comment by fifty-six** [comment]
wdym fatal? It's just something I didn't want to put in the program. Anyone who's modding their assembly beforehand should in theory be capable enough of reverting to vanilla before using the installer I would hope. If this feature is something actually needed, I prefer the SHA1 approach for the vanilla assembly at this point given that they *probably* are done with updates, though last time I said that they proceeded to update it again anyways

**Comment by HKLab** [comment]
I know

**Pull request closed without merging**
