### PR TITLE
Add WinGet CI

### PR DESCRIPTION
**Pull request by solomoncyj**

### CODE REVIEW

**Comment by solomoncyj** [comment]
make sure the following has een merged before merging
* https://github.com/microsoft/winget-pkgs/pull/124425

**Comment by solomoncyj** [comment]
Ready to merge

**Comment by fifty-six** [comment]
My username isn't spelled right in that, is that something I would just have to PR again?

**Comment by solomoncyj** [comment]
> My username isn't spelled right in that, is that something I would just have to PR again?

Sorry. Will fix once I have time

**Comment by solomoncyj** [comment]
* https://github.com/microsoft/winget-pkgs/pull/124822
wait for this one now

**Comment by solomoncyj** [comment]
Ready

**Comment by solomoncyj** [comment]
@fifty-six make sure to bind `${{ secrets.WINGET_TOKEN }}` to a github api token with `public_repo` scopes

**Pull request merged**
